name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      - name: Stop old container if exists
        run: |
          echo "Stopping and removing existing container (if any)..."
          docker stop my-node-app-container || true
          docker rm my-node-app-container || true

      - name: Run new container
        run: |
          echo "Running new container..."
          docker run -d \
            --name my-node-app-container \
            -p 32768:3000 \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
